package oxford

type AutoGenerated struct {
	Metadata struct {
	} `json:"metadata"`
	Results []struct {
		ID string `json:"id"`
		Language string `json:"language"`
		LexicalEntries []struct {
			Entries []struct {
				Etymologies []string `json:"etymologies"`
				GrammaticalFeatures []struct {
					Text string `json:"text"`
					Type string `json:"type"`
				} `json:"grammaticalFeatures"`
				HomographNumber string `json:"homographNumber"`
				Pronunciations []struct {
					AudioFile string `json:"audioFile"`
					Dialects []string `json:"dialects"`
					PhoneticNotation string `json:"phoneticNotation"`
					PhoneticSpelling string `json:"phoneticSpelling"`
					Regions []string `json:"regions"`
				} `json:"pronunciations"`
				Senses []struct {
					CrossReferenceMarkers []string `json:"crossReferenceMarkers"`
					CrossReferences []struct {
						ID string `json:"id"`
						Text string `json:"text"`
						Type string `json:"type"`
					} `json:"crossReferences"`
					Definitions []string `json:"definitions"`
					Domains []string `json:"domains"`
					Examples []struct {
						Definitions []string `json:"definitions"`
						Domains []string `json:"domains"`
						Regions []string `json:"regions"`
						Registers []string `json:"registers"`
						SenseIds []string `json:"senseIds"`
						Text string `json:"text"`
						Translations []struct {
							Domains []string `json:"domains"`
							GrammaticalFeatures []struct {
								Text string `json:"text"`
								Type string `json:"type"`
							} `json:"grammaticalFeatures"`
							Language string `json:"language"`
							Regions []string `json:"regions"`
							Registers []string `json:"registers"`
							Text string `json:"text"`
						} `json:"translations"`
					} `json:"examples"`
					ID string `json:"id"`
					Pronunciations []struct {
						AudioFile string `json:"audioFile"`
						Dialects []string `json:"dialects"`
						PhoneticNotation string `json:"phoneticNotation"`
						PhoneticSpelling string `json:"phoneticSpelling"`
						Regions []string `json:"regions"`
					} `json:"pronunciations"`
					Regions []string `json:"regions"`
					Registers []string `json:"registers"`
					Subsenses []struct {
					} `json:"subsenses"`
					Translations []struct {
						Domains []string `json:"domains"`
						GrammaticalFeatures []struct {
							Text string `json:"text"`
							Type string `json:"type"`
						} `json:"grammaticalFeatures"`
						Language string `json:"language"`
						Regions []string `json:"regions"`
						Registers []string `json:"registers"`
						Text string `json:"text"`
					} `json:"translations"`
					VariantForms []struct {
						Regions []string `json:"regions"`
						Text string `json:"text"`
					} `json:"variantForms"`
				} `json:"senses"`
				VariantForms []struct {
					Regions []string `json:"regions"`
					Text string `json:"text"`
				} `json:"variantForms"`
			} `json:"entries"`
			GrammaticalFeatures []struct {
				Text string `json:"text"`
				Type string `json:"type"`
			} `json:"grammaticalFeatures"`
			Language string `json:"language"`
			LexicalCategory string `json:"lexicalCategory"`
			Pronunciations []struct {
				AudioFile string `json:"audioFile"`
				Dialects []string `json:"dialects"`
				PhoneticNotation string `json:"phoneticNotation"`
				PhoneticSpelling string `json:"phoneticSpelling"`
				Regions []string `json:"regions"`
			} `json:"pronunciations"`
			Text string `json:"text"`
			VariantForms []struct {
				Regions []string `json:"regions"`
				Text string `json:"text"`
			} `json:"variantForms"`
		} `json:"lexicalEntries"`
		Pronunciations []struct {
			AudioFile string `json:"audioFile"`
			Dialects []string `json:"dialects"`
			PhoneticNotation string `json:"phoneticNotation"`
			PhoneticSpelling string `json:"phoneticSpelling"`
			Regions []string `json:"regions"`
		} `json:"pronunciations"`
		Type string `json:"type"`
		Word string `json:"word"`
	} `json:"results"`
}
